use_frameworks!

target 'ZBFancyCollectionView_Example' do
  pod 'ZBFancyCollectionView', :path => '../'
  pod 'Masonry'  
  target 'ZBFancyCollectionView_Tests' do
    inherit! :search_paths

  end
end
